spring:
  datasource:
    url: 'jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}'
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder:
                TRACE
